"""auto update

Revision ID: 1363d5c61ec3
Revises: 630c9b2ff30d
Create Date: 2026-07-19 01:59:50.528565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1363d5c61ec3'
down_revision: Union[str, Sequence[str], None] = '630c9b2ff30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.String(), nullable=False),
    sa.Column('output_text', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_id'), 'agent_executions', ['id'], unique=False)
    op.create_table('mcp_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('mcp_tool_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='disconnected', nullable=True),
    sa.Column('last_ping_at', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_connections_id'), 'mcp_connections', ['id'], unique=False)
    op.create_table('tenant_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), server_default='member', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_members_id'), 'tenant_members', ['id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), server_default='free', nullable=True),
    sa.Column('max_tokens_per_month', sa.Integer(), server_default='1000000', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('completion_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('cost_credits', sa.Float(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_id'), 'usage_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_tenant_members_id'), table_name='tenant_members')
    op.drop_table('tenant_members')
    op.drop_index(op.f('ix_mcp_connections_id'), table_name='mcp_connections')
    op.drop_table('mcp_connections')
    op.drop_index(op.f('ix_agent_executions_id'), table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###